### ISSUE TITLE
Mistake in README

### ISSUE THREAD

**Issue by me-abhinav** [microsoft/DarkModeKit#41]
The README needs to be corrected. Following is not a `UIColor` extension. I think it should be `UIImage` extension.

```swift
extension UIColor {
    init(_: DMNamespace, light: UIImage, dark: UIImage)
}
```
https://github.com/microsoft/DarkModeKit/blob/master/README.md#images

**Comment by Petr-2019** [comment]
@me-abhinav Thanks for reporting this! We'll fix this.
