### ISSUE TITLE
Use image extension can be crash!

### ISSUE THREAD

**Issue by richful** [microsoft/DarkModeKit#49]
when I try use UImage-dark in the demo, I receive a crash err. next the code

let lightImage = UIImage(named: "light")!
let darkImage = UIImage(named: "dark")!
let image = UIImage(.dm, light: lightImage, dark: darkImage)

can't find image ,the crash err is:
### '+[UIImage dm_namespace:dm_imageWithLightImage:darkImage:]: unrecognized selector sent to class 0x7fff898bd368'

**Comment by yangwei0401** [comment]
I have the same issue

**Comment by kylinroc** [comment]
@richful @yangwei0401 Please use new version 0.4.0

**Comment by anysome** [comment]
Pod repo can't fetch 0.4.0

**Comment by imWildCat** [comment]
@anysome Thanks for reporting. This has been fixed now.
